### ISSUE TITLE
Handwritten support?

### ISSUE THREAD

**Issue by aboozaid** [HusseinYoussef/Arabic-OCR#1]
I just looked at the datasets that you used and found that it only use computer typed text not handwritten by a human, is this correct?!

**Comment by aboozaid** [comment]
seems it only supports printed typed text.

**Comment by HusseinYoussef** [comment]
Sorry for the late reply.
Yes, It supports only machine printed text for now as stated in the
repository description "converts images of typed text". Sorry if it was
unclear.
