### ISSUE TITLE
OCR unable to read the input image for text detection uint error

### ISSUE THREAD

**Issue by bilalbaloch1** [HusseinYoussef/Arabic-OCR#10]
I have tried to detect Arabic from Aljazeera news snaps but the code failed to read the file. The code is restricted to read **8- bit depth** jpeg or png image. However, I have used the 24-bit depth jpeg image and 8-bit bitmap image (added .bmp in list) but still that uint error. Is your code is supporting a specific Arabic font? and how to resolve this bit depth issue. Please guide thanks.

![1](https://user-images.githubusercontent.com/50079497/96332804-a0d2e980-107f-11eb-939a-6659250589d0.PNG)
![2](https://user-images.githubusercontent.com/50079497/96332808-a29cad00-107f-11eb-843c-56c3d0906d3a.PNG)

**Comment by bilalbaloch1** [comment]
Waiting for the kind reply from the source code author.

**Comment by HusseinYoussef** [comment]
can you copy the error here?
I tried .bmp images and it worked, can you send me the images you are using in .zip file so I can try them?
Is the error related to the img_idx?

**Comment by bilalbaloch1** [comment]
I have used the above mentioned images snapped from Aljazeera Arabic. Yes the image is related to img_idx.

**Comment by HusseinYoussef** [comment]
I removed img_idx entirely from the code since it isn't important at all, can you clone and try again?
and yes, we support fonts that are very similar to the one used in the dataset.

**Comment by HusseinYoussef** [comment]
So... Any updates?
