### ISSUE TITLE
need working example

### ISSUE THREAD

**Issue by jbjaveed** [HusseinYoussef/Arabic-OCR#6]
i'm trying to use this code, but i get empty output. I think there is something wrong with my image,not sure. can you provide some sample working test image

**Comment by jbjaveed** [comment]
nevermind! found it

**Comment by HusseinYoussef** [comment]
Most probably it was a .jpg image not .png or you weren't inside src directory while running the command. Anyway I have added a working example and it now supports both .png and .jpg
and remember you have to be in the src directory before running the command `python OCR.py`.
