### ISSUE TITLE
Training Process is stuck after breakpoints

### ISSUE THREAD

**Issue by sanjranicsd** [HusseinYoussef/Arabic-OCR#9]
After reading all images from dataset the training process is stuck on scores[ ] Pdb. Please describe is the training process is running in background? or debugger is unable to continue the process. Moreover, how much time will it require to train the models?

**Comment by HusseinYoussef** [comment]
You could remove the breakpoints and try without them.
I removed them since they existed only for testing purposes, and added a progress bar for the training. Hence, try again and let me know.
As for the training process, it takes about 15 minutes (max) depending on the model and the machine.
